<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AudioParsing.Console</RootNamespace>
    <AssemblyName>AudioParsing.Console</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AudioParsing.Core\AudioParsing.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
